spring.application.name=bank_rest


#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/contact_db
spring.datasource.username=postgres_postgres
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.postgresql.Driver

#jpa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#liquibase
spring.liquibase.enabled=false